version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/var/lib/mongodb/data

  server:
    build: .
    environment:
      - MONGO_URL=mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"

  nginx:
    image: nginx
    volumes:
      - ./index.html:/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - "server:server"
    command: ["nginx", "-g", "daemon off;"]
